/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.jiuqi.np.definition.internal.anno.DBAnno$DBField
 *  com.jiuqi.nr.conditionalstyle.facade.impl.ConditionalStyleImpl
 */
package com.jiuqi.nr.definition.deploy.common;

import com.jiuqi.np.definition.internal.anno.DBAnno;
import com.jiuqi.nr.conditionalstyle.facade.impl.ConditionalStyleImpl;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public interface ParamDeploySQL {
    public static final String QUERY_CONDITION_LINK_BY_FORM = "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ? AND F.FL_FORM_KEY = ?";
    public static final String QUERY_CONDITION_LINK_BY_NULLFORM = "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ? AND F.FL_FORM_KEY IS NULL";
    public static final String QUERY_CONDITION_LINK_BY_FORMULASCHEME = "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ?";
    public static final String QUERY_CONDITION_LINK_BY_FORMSCHEME = "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY LEFT JOIN NR_PARAM_FORMULASCHEME_DES S ON F.FL_SCHEME_KEY = S.FS_KEY WHERE S.FS_FORM_SCHEME_KEY = ?";

    public String getDeploySQL();

    public String getRollbackSQL();

    public String getDescription();

    public static List<String> getFieldNames(Class<?> clz) {
        Field[] fields;
        ArrayList<String> fieldNames = new ArrayList<String>();
        for (Field field : fields = clz.getDeclaredFields()) {
            if (!field.isAnnotationPresent(DBAnno.DBField.class)) continue;
            DBAnno.DBField fieldAnno = field.getAnnotation(DBAnno.DBField.class);
            fieldNames.add(fieldAnno.dbField());
        }
        return fieldNames;
    }

    public static enum ConditionalStyle implements ParamDeploySQL
    {
        DELETE_STYLE("DELETE FROM NR_PARAM_CONDITIONAL_STYLE WHERE CS_KEY IN ( SELECT CS_KEY FROM (    SELECT R.CS_KEY FROM NR_PARAM_CONDITIONAL_STYLE R    LEFT JOIN NR_PARAM_CONDITIONAL_STYLE_DES D ON R.CS_KEY = D.CS_KEY    LEFT JOIN NR_PARAM_FORM F ON R.CS_FORM_KEY = F.FM_KEY    WHERE F.FM_FORMSCHEME = ? AND (D.CS_KEY IS NULL OR R.CS_UPDATE_TIME <> D.CS_UPDATE_TIME) ) T)", "", "\u5220\u9664\u6761\u4ef6\u6837\u5f0f"),
        DELETE_STYLE_BY_FORM("DELETE FROM NR_PARAM_CONDITIONAL_STYLE WHERE CS_FORM_KEY = ?", "", "\u5220\u9664\u6761\u4ef6\u6837\u5f0f"),
        INSERT_STYLE("INSERT INTO NR_PARAM_CONDITIONAL_STYLE (" + String.join((CharSequence)",", ParamDeploySQL.getFieldNames(ConditionalStyleImpl.class)) + ") SELECT " + ParamDeploySQL.getFieldNames(ConditionalStyleImpl.class).stream().map(n -> "D." + n).collect(Collectors.joining(",")) + " FROM NR_PARAM_CONDITIONAL_STYLE_DES D LEFT JOIN NR_PARAM_CONDITIONAL_STYLE R ON D.CS_KEY = R.CS_KEY LEFT JOIN NR_PARAM_FORM_DES F ON F.FM_KEY = D.CS_FORM_KEY WHERE F.FM_FORMSCHEME = ? AND R.CS_KEY IS NULL", "", "\u65b0\u589e\u6761\u4ef6\u6837\u5f0f"),
        INSERT_STYLE_BY_FORM("INSERT INTO NR_PARAM_CONDITIONAL_STYLE (" + String.join((CharSequence)",", ParamDeploySQL.getFieldNames(ConditionalStyleImpl.class)) + ") SELECT " + String.join((CharSequence)",", ParamDeploySQL.getFieldNames(ConditionalStyleImpl.class)) + " FROM NR_PARAM_CONDITIONAL_STYLE_DES WHERE CS_FORM_KEY = ?", "", "\u65b0\u589e\u6761\u4ef6\u6837\u5f0f");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private ConditionalStyle(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }

    public static enum AnalysisForm implements ParamDeploySQL
    {
        DELETE("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG    WHERE R.BD_KEY = ? AND R.BD_CODE = ? AND (D.BD_KEY IS NULL OR R.BD_UPDATETIME <> D.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u5206\u6790\u8868\u53c2\u6570"),
        DELETE_JOIN_FORM("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG    LEFT JOIN NR_PARAM_FORM F ON R.BD_KEY = F.FM_KEY    WHERE F.FM_FORMSCHEME = ? AND R.BD_CODE = ? AND (D.BD_KEY IS NULL OR R.BD_UPDATETIME <> D.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u5206\u6790\u8868\u53c2\u6570"),
        DELETE_JOIN_GROUP("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG    LEFT JOIN NR_PARAM_FORMGROUP G ON R.BD_KEY = G.FG_KEY    WHERE G.FG_FORM_SCHEME_KEY = ? AND R.BD_CODE = ? AND (D.BD_KEY IS NULL OR R.BD_UPDATETIME <> D.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u5206\u6790\u8868\u53c2\u6570"),
        INSERT("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG WHERE D.BD_KEY = ? AND D.BD_CODE = ? AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u5206\u6790\u8868\u53c2\u6570"),
        INSERT_JOIN_FORM("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG LEFT JOIN NR_PARAM_FORM F ON R.BD_KEY = F.FM_KEY WHERE F.FM_FORMSCHEME = ? AND D.BD_CODE = ? AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u5206\u6790\u8868\u53c2\u6570"),
        INSERT_JOIN_GROUP("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG LEFT JOIN NR_PARAM_FORMGROUP_DES G ON D.BD_KEY = G.FG_KEY WHERE G.FG_FORM_SCHEME_KEY = ? AND D.BD_CODE = ? AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u5206\u6790\u8868\u53c2\u6570");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private AnalysisForm(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }

    public static enum FormulaCondition implements ParamDeploySQL
    {
        DELETE_LINK(String.format("DELETE FROM NR_PARAM_CONDITION_LINK WHERE CL_KEY IN (SELECT CL_KEY FROM (%s) T)", "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY LEFT JOIN NR_PARAM_FORMULASCHEME_DES S ON F.FL_SCHEME_KEY = S.FS_KEY WHERE S.FS_FORM_SCHEME_KEY = ?"), "", "\u5220\u9664\u9002\u7528\u6761\u4ef6"),
        DELETE_LINK_BY_FORMULASCHEME(String.format("DELETE FROM NR_PARAM_CONDITION_LINK WHERE CL_KEY IN (SELECT CL_KEY FROM (%s) T)", "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ?"), "", "\u5220\u9664\u9002\u7528\u6761\u4ef6"),
        DELETE_LINK_BY_FORM(String.format("DELETE FROM NR_PARAM_CONDITION_LINK WHERE CL_KEY IN (SELECT CL_KEY FROM (%s) T)", "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ? AND F.FL_FORM_KEY = ?"), "", "\u5220\u9664\u9002\u7528\u6761\u4ef6"),
        DELETE_LINK_BY_NULLFORM(String.format("DELETE FROM NR_PARAM_CONDITION_LINK WHERE CL_KEY IN (SELECT CL_KEY FROM (%s) T)", "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ? AND F.FL_FORM_KEY IS NULL"), "", "\u5220\u9664\u9002\u7528\u6761\u4ef6"),
        DELETE(String.format("DELETE FROM NR_PARAM_FM_CONDITION WHERE FC_KEY IN (%s)", "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY LEFT JOIN NR_PARAM_FORMULASCHEME_DES S ON F.FL_SCHEME_KEY = S.FS_KEY WHERE S.FS_FORM_SCHEME_KEY = ?"), "", "\u5220\u9664\u9002\u7528\u6761\u4ef6\u94fe\u63a5"),
        DELETE_BY_FORMULASCHEME(String.format("DELETE FROM NR_PARAM_FM_CONDITION WHERE FC_KEY IN (%s)", "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ?"), "", "\u5220\u9664\u9002\u7528\u6761\u4ef6\u94fe\u63a5"),
        DELETE_BY_FORM(String.format("DELETE FROM NR_PARAM_FM_CONDITION WHERE FC_KEY IN (%s)", "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ? AND F.FL_FORM_KEY = ?"), "", "\u5220\u9664\u9002\u7528\u6761\u4ef6\u94fe\u63a5"),
        DELETE_BY_NULLFORM(String.format("DELETE FROM NR_PARAM_FM_CONDITION WHERE FC_KEY IN (%s)", "SELECT R.CL_KEY FROM NR_PARAM_CONDITION_LINK R LEFT JOIN NR_PARAM_FORMULA_DES F ON R.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ? AND F.FL_FORM_KEY IS NULL"), "", "\u5220\u9664\u9002\u7528\u6761\u4ef6\u94fe\u63a5"),
        INSERT("INSERT INTO NR_PARAM_FM_CONDITION SELECT D.* FROM NR_PARAM_FM_CONDITION_DES D WHERE D.FC_KEY IN (SELECT L.CL_KEY                    FROM NR_PARAM_CONDITION_LINK_DES L                             JOIN NR_PARAM_FORMULA_DES F ON F.FL_KEY = L.CL_FM_KEY                             JOIN NR_PARAM_FORMULASCHEME_DES S ON S.FS_KEY = F.FL_SCHEME_KEY                    WHERE S.FS_FORM_SCHEME_KEY = ?                    GROUP BY L.CL_KEY)", "", "\u65b0\u589e\u9002\u7528\u6761\u4ef6"),
        INSERT_BY_FORMULASCHEME("INSERT INTO NR_PARAM_FM_CONDITION SELECT D.* FROM NR_PARAM_FM_CONDITION_DES D WHERE D.FC_KEY IN (SELECT L.CL_KEY                    FROM NR_PARAM_CONDITION_LINK_DES L                             JOIN NR_PARAM_FORMULA_DES F ON F.FL_KEY = L.CL_FM_KEY                    WHERE F.FL_SCHEME_KEY = ?                    GROUP BY L.CL_KEY)", "", "\u65b0\u589e\u9002\u7528\u6761\u4ef6"),
        INSERT_BY_FORM("INSERT INTO NR_PARAM_FM_CONDITION SELECT D.* FROM NR_PARAM_FM_CONDITION_DES D WHERE D.FC_KEY IN (SELECT L.CL_KEY                    FROM NR_PARAM_CONDITION_LINK_DES L                             JOIN NR_PARAM_FORMULA_DES F ON F.FL_KEY = L.CL_FM_KEY                    WHERE F.FL_SCHEME_KEY = ?                      AND F.FL_FORM_KEY = ?                    GROUP BY L.CL_KEY)", "", "\u65b0\u589e\u9002\u7528\u6761\u4ef6"),
        INSERT_BY_NULLFORM("INSERT INTO NR_PARAM_FM_CONDITION SELECT D.* FROM NR_PARAM_FM_CONDITION_DES D WHERE D.FC_KEY IN (SELECT L.CL_KEY                    FROM NR_PARAM_CONDITION_LINK_DES L                             JOIN NR_PARAM_FORMULA_DES F ON F.FL_KEY = L.CL_FM_KEY                    WHERE F.FL_SCHEME_KEY = ?                      AND F.FL_FORM_KEY IS NULL                    GROUP BY L.CL_KEY)", "", "\u65b0\u589e\u9002\u7528\u6761\u4ef6"),
        INSERT_LINK("INSERT INTO NR_PARAM_CONDITION_LINK SELECT D.* FROM NR_PARAM_CONDITION_LINK_DES D LEFT JOIN NR_PARAM_FORMULA_DES F ON D.CL_FM_KEY = F.FL_KEY LEFT JOIN NR_PARAM_FORMULASCHEME_DES S ON S.FS_KEY = F.FL_SCHEME_KEY WHERE S.FS_FORM_SCHEME_KEY = ?", "", "\u65b0\u589e\u9002\u7528\u6761\u4ef6\u94fe\u63a5"),
        INSERT_LINK_BY_FORMULASCHEME("INSERT INTO NR_PARAM_CONDITION_LINK SELECT D.* FROM NR_PARAM_CONDITION_LINK_DES D LEFT JOIN NR_PARAM_FORMULA_DES F ON D.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ?", "", "\u65b0\u589e\u9002\u7528\u6761\u4ef6\u94fe\u63a5"),
        INSERT_LINK_BY_FORM("INSERT INTO NR_PARAM_CONDITION_LINK SELECT D.* FROM NR_PARAM_CONDITION_LINK_DES D LEFT JOIN NR_PARAM_FORMULA_DES F ON D.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ? AND F.FL_FORM_KEY = ?", "", "\u65b0\u589e\u9002\u7528\u6761\u4ef6\u94fe\u63a5"),
        INSERT_LINK_BY_NULLFORM("INSERT INTO NR_PARAM_CONDITION_LINK SELECT D.* FROM NR_PARAM_CONDITION_LINK_DES D LEFT JOIN NR_PARAM_FORMULA_DES F ON D.CL_FM_KEY = F.FL_KEY WHERE F.FL_SCHEME_KEY = ? AND F.FL_FORM_KEY IS NULL", "", "\u65b0\u589e\u9002\u7528\u6761\u4ef6\u94fe\u63a5");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private FormulaCondition(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }

    public static enum FormulaVariable implements ParamDeploySQL
    {
        DELETE_FORMULA_VARIABLE("DELETE FROM NR_PARAM_FORMULAVARIABLE WHERE FA_KEY IN ( SELECT FA_KEY FROM (    SELECT R.FA_KEY FROM NR_PARAM_FORMULAVARIABLE R    LEFT JOIN NR_PARAM_FORMULAVARIABLE_DES D ON R.FA_KEY = D.FA_KEY    WHERE R.FA_FS_KEY = ? AND (D.FA_KEY IS NULL OR R.FA_UPDATETIME <>  D.FA_UPDATETIME) ) T)", "", "\u5220\u9664\u516c\u5f0f\u53d8\u91cf"),
        INSERT_FORMULA_VARIABLE("INSERT INTO NR_PARAM_FORMULAVARIABLE SELECT D.* FROM NR_PARAM_FORMULAVARIABLE_DES D LEFT JOIN NR_PARAM_FORMULAVARIABLE R ON D.FA_KEY = R.FA_KEY WHERE D.FA_FS_KEY = ? AND R.FA_KEY IS NULL", "", "\u65b0\u589e\u516c\u5f0f\u53d8\u91cf");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private FormulaVariable(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }

    public static enum ReportTemplate implements ParamDeploySQL
    {
        DELETE_TEMPLATES_TAG("DELETE FROM NR_PARAM_RPT_TAG WHERE RT_RPT_KEY IN ( SELECT R.RT_KEY FROM NR_PARAM_REPORT_TEMPLATE R WHERE R.RT_FORMSCHEME_KEY = ?)", "", "\u5220\u9664\u62a5\u544a\u6a21\u677f\u6807\u7b7e"),
        DELETE_TEMPLATES("DELETE FROM NR_PARAM_REPORT_TEMPLATE WHERE RT_FORMSCHEME_KEY = ?", "", "\u5220\u9664\u62a5\u544a\u6a21\u677f"),
        INSERT_TEMPLATES_TAG("INSERT INTO NR_PARAM_RPT_TAG SELECT D.* FROM NR_PARAM_RPT_TAG_DES D LEFT JOIN NR_PARAM_REPORT_TEMPLATE_DES RT ON D.RT_RPT_KEY = RT.RT_KEY WHERE RT.RT_FORMSCHEME_KEY = ?", "", "\u65b0\u589e\u62a5\u544a\u6a21\u677f\u6807\u7b7e"),
        INSERT_TEMPLATES("INSERT INTO NR_PARAM_REPORT_TEMPLATE SELECT D.* FROM NR_PARAM_REPORT_TEMPLATE_DES D WHERE D.RT_FORMSCHEME_KEY = ?", "", "\u65b0\u589e\u62a5\u544a\u6a21\u677f"),
        DELETE_TEMPLATE_TAG("DELETE FROM NR_PARAM_RPT_TAG WHERE RT_RPT_KEY = ? ", "", "\u5220\u9664\u62a5\u544a\u6a21\u677f\u6807\u7b7e"),
        DELETE_TEMPLATE("DELETE FROM NR_PARAM_REPORT_TEMPLATE WHERE RT_KEY = ?", "", "\u5220\u9664\u62a5\u544a\u6a21\u677f"),
        INSERT_TEMPLATE_TAG("INSERT INTO NR_PARAM_RPT_TAG SELECT D.* FROM NR_PARAM_RPT_TAG_DES D WHERE D.RT_RPT_KEY = ?", "", "\u65b0\u589e\u62a5\u544a\u6a21\u677f\u6807\u7b7e"),
        INSERT_TEMPLATE("INSERT INTO NR_PARAM_REPORT_TEMPLATE SELECT D.* FROM NR_PARAM_REPORT_TEMPLATE_DES D WHERE D.RT_KEY = ?", "", "\u65b0\u589e\u62a5\u544a\u6a21\u677f");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private ReportTemplate(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }

    public static enum PrintTemplate implements ParamDeploySQL
    {
        DELETE_PRINT_TEMPLATE_BLOB("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_CODE IN ('PRINT_TEMPLATE_DATA', 'PRINT_LABLE_DATA') AND BD_KEY IN ( SELECT T.PT_KEY FROM NR_PARAM_PRINTTEMPLATE T WHERE T.PT_PRINT_SCHEME_KEY = ? AND T.PT_FORM_KEY = ? )", "", "\u5220\u9664\u6253\u5370\u6a21\u677f\u4e8c\u8fdb\u5236"),
        DELETE_PRINT_TEMPLATE("DELETE FROM NR_PARAM_PRINTTEMPLATE WHERE PT_PRINT_SCHEME_KEY = ? AND PT_FORM_KEY = ?", "", "\u5220\u9664\u6253\u5370\u6a21\u677f"),
        INSERT_PRINT_TEMPLATE_BLOB("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG LEFT JOIN NR_PARAM_PRINTTEMPLATE_DES T ON D.BD_KEY = T.PT_KEY WHERE T.PT_PRINT_SCHEME_KEY = ? AND T.PT_FORM_KEY = ? AND D.BD_CODE IN ('PRINT_TEMPLATE_DATA', 'PRINT_LABLE_DATA') AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u6253\u5370\u6a21\u677f\u4e8c\u8fdb\u5236"),
        INSERT_PRINT_TEMPLATE("INSERT INTO NR_PARAM_PRINTTEMPLATE SELECT D.* FROM NR_PARAM_PRINTTEMPLATE_DES D LEFT JOIN NR_PARAM_PRINTTEMPLATE R ON D.PT_KEY = R.PT_KEY WHERE D.PT_PRINT_SCHEME_KEY = ? AND D.PT_FORM_KEY = ? AND R.PT_KEY IS NULL", "", "\u65b0\u589e\u6253\u5370\u6a21\u677f");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private PrintTemplate(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }

    public static enum PrintScheme implements ParamDeploySQL
    {
        DELETE_PRINT_TEMPLATE_BLOB("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_CODE IN ('PRINT_TEMPLATE_DATA', 'PRINT_LABLE_DATA') AND BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG    LEFT JOIN NR_PARAM_PRINTTEMPLATE T ON R.BD_KEY = T.PT_KEY    WHERE T.PT_PRINT_SCHEME_KEY = ? AND R.BD_CODE IN ('PRINT_TEMPLATE_DATA', 'PRINT_LABLE_DATA') AND (D.BD_KEY IS NULL OR R.BD_UPDATETIME <> D.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u6253\u5370\u6a21\u677f\u4e8c\u8fdb\u5236"),
        DELETE_PRINT_TEMPLATE("DELETE FROM NR_PARAM_PRINTTEMPLATE WHERE PT_KEY IN ( SELECT PT_KEY FROM (    SELECT R.PT_KEY FROM NR_PARAM_PRINTTEMPLATE R    LEFT JOIN NR_PARAM_PRINTTEMPLATE_DES D ON R.PT_KEY = D.PT_KEY     WHERE R.PT_PRINT_SCHEME_KEY = ? AND (D.PT_KEY IS NULL OR R.PT_UPDATETIME <> D.PT_UPDATETIME) ) T)", "", "\u5220\u9664\u6253\u5370\u6a21\u677f"),
        DELETE_PRINT_EXCEL_SETTING("DELETE FROM NR_PARAM_PRINTSETTING WHERE PS_PRINT_SCHEME_KEY = ? ", "", "\u5220\u9664Excel\u6253\u5370\u8bbe\u7f6e"),
        INSERT_PRINT_TEMPLATE_BLOB("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG LEFT JOIN NR_PARAM_PRINTTEMPLATE_DES T ON D.BD_KEY = T.PT_KEY WHERE T.PT_PRINT_SCHEME_KEY = ? AND D.BD_CODE IN ('PRINT_TEMPLATE_DATA', 'PRINT_LABLE_DATA') AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u6253\u5370\u6a21\u677f\u4e8c\u8fdb\u5236"),
        INSERT_PRINT_TEMPLATE("INSERT INTO NR_PARAM_PRINTTEMPLATE SELECT D.* FROM NR_PARAM_PRINTTEMPLATE_DES D LEFT JOIN NR_PARAM_PRINTTEMPLATE R ON D.PT_KEY = R.PT_KEY WHERE D.PT_PRINT_SCHEME_KEY = ? AND R.PT_KEY IS NULL", "", "\u65b0\u589e\u6253\u5370\u6a21\u677f"),
        INSERT_PRINT_EXCEL_SETTING("INSERT INTO NR_PARAM_PRINTSETTING SELECT D.* FROM NR_PARAM_PRINTSETTING_DES D WHERE D.PS_PRINT_SCHEME_KEY = ?", "", "\u65b0\u589eExcel\u6253\u5370\u8bbe\u7f6e"),
        DELETE_PRINT_COMTEM_BLOB("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_CODE = 'PRINTS_COMTEM_DATA' AND BD_KEY IN ( SELECT BD_KEY FROM (    SELECT D.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_PRINTCOMTEM C ON R.BD_KEY = C.PC_KEY    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG    WHERE C.PC_PRINT_SCHEME_KEY = ? AND R.BD_CODE = 'PRINTS_COMTEM_DATA' AND (D.BD_KEY IS NULL OR R.BD_UPDATETIME <> D.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u6253\u5370\u6bcd\u7248\u4e8c\u8fdb\u5236"),
        DELETE_PRINT_COMTEM("DELETE FROM NR_PARAM_PRINTCOMTEM WHERE PC_KEY IN ( SELECT PC_KEY FROM (    SELECT R.PC_KEY FROM NR_PARAM_PRINTCOMTEM R    LEFT JOIN NR_PARAM_PRINTCOMTEM_DES D ON D.PC_KEY = R.PC_KEY    WHERE R.PC_PRINT_SCHEME_KEY = ? AND (D.PC_KEY IS NULL OR D.PC_UPDATE_TIME <> R.PC_UPDATE_TIME) ) T)", "", "\u5220\u9664\u6253\u5370\u6bcd\u7248"),
        INSERT_PRINT_COMTEM_BLOB("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG LEFT JOIN NR_PARAM_PRINTCOMTEM_DES C ON D.BD_KEY = C.PC_KEY WHERE C.PC_PRINT_SCHEME_KEY = ? AND D.BD_CODE = 'PRINTS_COMTEM_DATA' AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u6253\u5370\u6bcd\u7248"),
        INSERT_PRINT_COMTEM("INSERT INTO NR_PARAM_PRINTCOMTEM SELECT D.* FROM NR_PARAM_PRINTCOMTEM_DES D LEFT JOIN NR_PARAM_PRINTCOMTEM R ON D.PC_KEY = R.PC_KEY WHERE D.PC_PRINT_SCHEME_KEY = ? AND R.PC_KEY IS NULL", "", "\u65b0\u589e\u6253\u5370\u6bcd\u7248\u4e8c\u8fdb\u5236"),
        DELETE_PRINT_SCHEME_BLOB("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_CODE IN ('PRINTS_GATTHER_DATA', 'PRINTS_ATTR_DATA') AND BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG    WHERE R.BD_KEY = ? AND R.BD_CODE IN ('PRINTS_GATTHER_DATA', 'PRINTS_ATTR_DATA') AND (D.BD_KEY IS NULL OR R.BD_UPDATETIME <> D.BD_UPDATETIME)    GROUP BY R.BD_KEY) T)", "", "\u5220\u9664\u6253\u5370\u65b9\u6848\u4e8c\u8fdb\u5236"),
        DELETE_PRINT_SCHEME("DELETE FROM NR_PARAM_PRINTSCHEME WHERE PS_KEY IN ( SELECT PS_KEY FROM (    SELECT R.PS_KEY FROM NR_PARAM_PRINTSCHEME R    LEFT JOIN NR_PARAM_PRINTSCHEME_DES D ON R.PS_KEY = D.PS_KEY    WHERE R.PS_KEY = ? AND (D.PS_KEY IS NULL OR R.PS_UPDATETIME <> D.PS_UPDATETIME) ) T)", "", "\u5220\u9664\u6253\u5370\u65b9\u6848"),
        INSERT_PRINT_SCHEME_BLOB("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG WHERE D.BD_KEY = ? AND D.BD_CODE IN ('PRINTS_GATTHER_DATA', 'PRINTS_ATTR_DATA') AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u6253\u5370\u65b9\u6848\u4e8c\u8fdb\u5236"),
        INSERT_PRINT_SCHEME("INSERT INTO NR_PARAM_PRINTSCHEME SELECT D.* FROM NR_PARAM_PRINTSCHEME_DES D  LEFT JOIN NR_PARAM_PRINTSCHEME R ON D.PS_KEY = R.PS_KEY WHERE D.PS_KEY = ? AND R.PS_KEY IS NULL", "", "\u65b0\u589e\u6253\u5370\u65b9\u6848");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private PrintScheme(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }

    public static enum Formula implements ParamDeploySQL
    {
        DELETE_FORMULA("DELETE FROM NR_PARAM_FORMULA WHERE FL_KEY IN ( SELECT FL_KEY FROM (    SELECT R.FL_KEY FROM NR_PARAM_FORMULA R    LEFT JOIN NR_PARAM_FORMULA_DES D ON R.FL_KEY = D.FL_KEY    WHERE R.FL_SCHEME_KEY = ? AND R.FL_FORM_KEY = ? AND (D.FL_KEY IS NULL OR R.FL_UPDATETIME <> D.FL_UPDATETIME) ) T)", "", "\u5220\u9664\u516c\u5f0f"),
        INSERT_FORMULA("INSERT INTO NR_PARAM_FORMULA SELECT D.* FROM NR_PARAM_FORMULA_DES D LEFT JOIN NR_PARAM_FORMULA R ON D.FL_KEY = R.FL_KEY WHERE D.FL_SCHEME_KEY = ? AND D.FL_FORM_KEY = ? AND R.FL_KEY IS NULL", "", "\u65b0\u589e\u516c\u5f0f"),
        DELETE_FORMULA_FORM_ISNULL("DELETE FROM NR_PARAM_FORMULA WHERE FL_KEY IN ( SELECT FL_KEY FROM (    SELECT R.FL_KEY FROM NR_PARAM_FORMULA R    LEFT JOIN NR_PARAM_FORMULA_DES D ON R.FL_KEY = D.FL_KEY    WHERE R.FL_SCHEME_KEY = ? AND R.FL_FORM_KEY IS NULL AND (D.FL_KEY IS NULL OR R.FL_UPDATETIME <> D.FL_UPDATETIME) ) T)", "", "\u5220\u9664\u516c\u5f0f"),
        INSERT_FORMULA_FORM_ISNULL("INSERT INTO NR_PARAM_FORMULA SELECT D.* FROM NR_PARAM_FORMULA_DES D LEFT JOIN NR_PARAM_FORMULA R ON D.FL_KEY = R.FL_KEY WHERE D.FL_SCHEME_KEY = ? AND D.FL_FORM_KEY IS NULL AND R.FL_KEY IS NULL", "", "\u65b0\u589e\u516c\u5f0f");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private Formula(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }

    public static enum FormulaScheme implements ParamDeploySQL
    {
        DELETE_FORMULA_SCHEME("DELETE FROM NR_PARAM_FORMULASCHEME WHERE FS_KEY IN ( SELECT FS_KEY FROM (    SELECT R.FS_KEY FROM NR_PARAM_FORMULASCHEME R    LEFT JOIN NR_PARAM_FORMULASCHEME_DES D ON R.FS_KEY = D.FS_KEY     WHERE R.FS_KEY = ? AND (D.FS_KEY IS NULL OR R.FS_UPDATETIME <> D.FS_UPDATETIME) ) T)", "", "\u5220\u9664\u516c\u5f0f\u65b9\u6848"),
        INSERT_FORMULA_SCHEME("INSERT INTO NR_PARAM_FORMULASCHEME SELECT D.* FROM NR_PARAM_FORMULASCHEME_DES D LEFT JOIN NR_PARAM_FORMULASCHEME R ON D.FS_KEY  = R.FS_KEY WHERE D.FS_KEY = ? AND R.FS_KEY IS NULL", "", "\u65b0\u589e\u516c\u5f0f\u65b9\u6848"),
        DELETE_FORMULA("DELETE FROM NR_PARAM_FORMULA WHERE FL_KEY IN ( SELECT FL_KEY FROM (    SELECT R.FL_KEY FROM NR_PARAM_FORMULA R    LEFT JOIN NR_PARAM_FORMULA_DES D ON R.FL_KEY = D.FL_KEY    WHERE R.FL_SCHEME_KEY = ? AND (D.FL_KEY IS NULL OR R.FL_UPDATETIME <> D.FL_UPDATETIME) ) T)", "", "\u5220\u9664\u516c\u5f0f"),
        INSERT_FORMULA("INSERT INTO NR_PARAM_FORMULA SELECT D.* FROM NR_PARAM_FORMULA_DES D LEFT JOIN NR_PARAM_FORMULA R ON D.FL_KEY = R.FL_KEY WHERE D.FL_SCHEME_KEY = ? AND R.FL_KEY IS NULL", "", "\u65b0\u589e\u516c\u5f0f");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private FormulaScheme(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }

    public static enum Form implements ParamDeploySQL
    {
        DELETE_LINK_BLOB("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_CODE = 'ATTACHMENT' AND BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG    LEFT JOIN NR_PARAM_DATALINK L ON R.BD_KEY = L.DL_KEY    LEFT JOIN NR_PARAM_DATAREGION DR ON L.DL_REGION_KEY = DR.DR_KEY    WHERE DR.DR_FORM_KEY = ? AND R.BD_CODE = 'ATTACHMENT' AND (D.BD_KEY IS NULL OR R.BD_UPDATETIME <> D.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u94fe\u63a5\u4e8c\u8fdb\u5236"),
        DELETE_LINK("DELETE FROM NR_PARAM_DATALINK WHERE DL_KEY IN ( SELECT DL_KEY FROM (    SELECT R.DL_KEY FROM NR_PARAM_DATALINK R    LEFT JOIN NR_PARAM_DATALINK_DES D ON R.DL_KEY = D.DL_KEY    LEFT JOIN NR_PARAM_DATAREGION DR ON DR.DR_KEY = R.DL_REGION_KEY    WHERE DR.DR_FORM_KEY = ? AND (D.DL_KEY IS NULL OR D.DL_UPDATETIME <> R.DL_UPDATETIME) ) T)", "", "\u5220\u9664\u94fe\u63a5"),
        INSERT_LINK_BLOB("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON D.BD_KEY = R.BD_KEY AND D.BD_CODE = R.BD_CODE AND R.BD_LANG = D.BD_LANG LEFT JOIN NR_PARAM_DATALINK_DES L ON D.BD_KEY = L.DL_KEY LEFT JOIN NR_PARAM_DATAREGION_DES DR ON DR.DR_KEY = L.DL_REGION_KEY WHERE DR.DR_FORM_KEY = ? AND D.BD_CODE = 'ATTACHMENT' AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u94fe\u63a5\u4e8c\u8fdb\u5236"),
        INSERT_LINK("INSERT INTO NR_PARAM_DATALINK SELECT D.* FROM NR_PARAM_DATALINK_DES D LEFT JOIN NR_PARAM_DATALINK R ON D.DL_KEY = R.DL_KEY LEFT JOIN NR_PARAM_DATAREGION_DES DR ON D.DL_REGION_KEY = DR.DR_KEY WHERE DR.DR_FORM_KEY = ? AND R.DL_KEY IS NULL", "", "\u65b0\u589e\u94fe\u63a5"),
        DELETE_LINK_MAPPING("DELETE FROM NR_PARAM_DATALINKMAPPING WHERE FM_KEY = ?", "", "\u5220\u9664\u5173\u8054\u679a\u4e3e"),
        INSERT_LINK_MAPPING("INSERT INTO NR_PARAM_DATALINKMAPPING SELECT M.* FROM NR_PARAM_DATALINKMAPPING_DES M WHERE M.FM_KEY = ?", "", "\u65b0\u589e\u5173\u8054\u679a\u4e3e"),
        DELETE_REGION_SETTING_BLOB("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_CODE IN ('REGION_TAB', 'REGION_ORDER', 'BIG_REGION_CARD', 'REGION_LT_ROW_STYLES', 'REGION_LT_COLUMN_STYLES') AND BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG    LEFT JOIN NR_PARAM_DATAREGION DR ON DR.DR_REGION_SETTING = R.BD_KEY    WHERE DR.DR_FORM_KEY = ? AND R.BD_CODE IN ('REGION_TAB', 'REGION_ORDER', 'BIG_REGION_CARD', 'REGION_LT_ROW_STYLES', 'REGION_LT_COLUMN_STYLES') AND (D.BD_KEY IS NULL OR R.BD_UPDATETIME <> D.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u533a\u57df\u8bbe\u7f6e\u4e8c\u8fdb\u5236"),
        DELETE_REGION_SETTING("DELETE FROM NR_PARAM_REGIONSETTING WHERE RS_KEY IN ( SELECT RS_KEY FROM (    SELECT R.RS_KEY FROM NR_PARAM_REGIONSETTING R    LEFT JOIN NR_PARAM_REGIONSETTING_DES D ON R.RS_KEY = D.RS_KEY    LEFT JOIN NR_PARAM_DATAREGION DR ON DR.DR_REGION_SETTING = R.RS_KEY    WHERE DR.DR_FORM_KEY = ? AND (D.RS_KEY IS NULL OR R.RS_UPDATETIME <> D.RS_UPDATETIME) ) T)", "", "\u5220\u9664\u533a\u57df\u8bbe\u7f6e"),
        DELETE_REGION("DELETE FROM NR_PARAM_DATAREGION WHERE DR_KEY IN ( SELECT DR_KEY FROM ( SELECT R.DR_KEY FROM NR_PARAM_DATAREGION R LEFT JOIN NR_PARAM_DATAREGION_DES D ON R.DR_KEY = D.DR_KEY WHERE R.DR_FORM_KEY = ? AND (D.DR_KEY IS NULL OR R.DR_UPDATETIME <> D.DR_UPDATETIME) ) T)", "", "\u5220\u9664\u533a\u57df"),
        INSERT_REGION_SETTING_BLOB("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON D.BD_KEY = R.BD_KEY AND D.BD_CODE = R.BD_CODE AND R.BD_LANG = D.BD_LANG LEFT JOIN NR_PARAM_DATAREGION_DES DR ON D.BD_KEY = DR.DR_REGION_SETTING WHERE DR.DR_FORM_KEY = ? AND D.BD_CODE IN ('REGION_TAB', 'REGION_ORDER', 'BIG_REGION_CARD', 'REGION_LT_ROW_STYLES', 'REGION_LT_COLUMN_STYLES') AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u533a\u57df\u8bbe\u7f6e\u4e8c\u8fdb\u5236"),
        INSERT_REGION_SETTING("INSERT INTO NR_PARAM_REGIONSETTING SELECT D.* FROM NR_PARAM_REGIONSETTING_DES D LEFT JOIN NR_PARAM_REGIONSETTING R ON D.RS_KEY = R.RS_KEY LEFT JOIN NR_PARAM_DATAREGION_DES DR ON D.RS_KEY = DR.DR_REGION_SETTING WHERE DR.DR_FORM_KEY = ? AND R.RS_KEY IS NULL", "", "\u65b0\u589e\u533a\u57df\u8bbe\u7f6e"),
        INSERT_REGION("INSERT INTO NR_PARAM_DATAREGION SELECT D.* FROM NR_PARAM_DATAREGION_DES D LEFT JOIN NR_PARAM_DATAREGION R ON R.DR_KEY = D.DR_KEY WHERE D.DR_FORM_KEY = ? AND R.DR_KEY IS NULL", "", "\u65b0\u589e\u533a\u57df\u8bbe\u7f6e"),
        DELETE_FORM_BLOB("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_CODE IN ('FORM_DATA', 'FILLING_GUIDE', 'BIG_SURVEY_DATA', 'BIG_SCRIPT_EDITOR') AND BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON D.BD_KEY = R.BD_KEY AND D.BD_CODE = R.BD_CODE AND R.BD_LANG = D.BD_LANG    WHERE R.BD_KEY = ? AND R.BD_CODE IN ('FORM_DATA', 'FILLING_GUIDE', 'BIG_SURVEY_DATA', 'BIG_SCRIPT_EDITOR') AND (D.BD_KEY IS NULL OR D.BD_UPDATETIME <> R.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u62a5\u8868\u4e8c\u8fdb\u5236"),
        DELETE_FORM("DELETE FROM NR_PARAM_FORM WHERE FM_KEY IN ( SELECT FM_KEY FROM (    SELECT R.FM_KEY FROM NR_PARAM_FORM R    LEFT JOIN NR_PARAM_FORM_DES D ON R.FM_KEY = D.FM_KEY    WHERE R.FM_KEY = ? AND (D.FM_KEY IS NULL OR R.FM_UPDATETIME <> D.FM_UPDATETIME) ) T)", "", "\u5220\u9664\u62a5\u8868"),
        INSERT_FORM_BLOB("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON D.BD_KEY = R.BD_KEY AND D.BD_CODE = R.BD_CODE AND R.BD_LANG = D.BD_LANG WHERE D.BD_KEY = ? AND D.BD_CODE IN ('FORM_DATA', 'FILLING_GUIDE', 'BIG_SURVEY_DATA', 'BIG_SCRIPT_EDITOR') AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u62a5\u8868\u4e8c\u8fdb\u5236"),
        INSERT_FORM("INSERT INTO NR_PARAM_FORM SELECT D.* FROM NR_PARAM_FORM_DES D LEFT JOIN NR_PARAM_FORM R ON D.FM_KEY = R.FM_KEY WHERE D.FM_KEY = ? AND R.FM_KEY IS NULL", "", "\u65b0\u589e\u62a5\u8868"),
        DELETE_FORM_GROUP_LINK("DELETE FROM NR_PARAM_FORMGROUPLINK WHERE FGL_FORM_KEY = ?", "", "\u5220\u9664\u62a5\u8868\u4e0e\u5206\u7ec4\u7684\u94fe\u63a5"),
        INSERT_FORM_GROUP_LINK("INSERT INTO NR_PARAM_FORMGROUPLINK SELECT D.* FROM NR_PARAM_FORMGROUPLINK_DES D WHERE D.FGL_FORM_KEY = ?", "", "\u65b0\u589e\u62a5\u8868\u4e0e\u5206\u7ec4\u7684\u94fe\u63a5");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private Form(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }

    public static enum FormScheme implements ParamDeploySQL
    {
        DELETE_LINK_BLOB("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_CODE = 'ATTACHMENT' AND BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG    LEFT JOIN NR_PARAM_DATALINK L ON R.BD_KEY = L.DL_KEY    LEFT JOIN NR_PARAM_DATAREGION DR ON L.DL_REGION_KEY = DR.DR_KEY    LEFT JOIN NR_PARAM_FORM F ON DR.DR_FORM_KEY = F.FM_KEY    WHERE F.FM_FORMSCHEME = ? AND R.BD_CODE = 'ATTACHMENT' AND (D.BD_KEY IS NULL OR R.BD_UPDATETIME <> D.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u94fe\u63a5\u4e8c\u8fdb\u5236"),
        DELETE_LINK("DELETE FROM NR_PARAM_DATALINK WHERE DL_KEY IN ( SELECT DL_KEY FROM (    SELECT R.DL_KEY FROM NR_PARAM_DATALINK R    LEFT JOIN NR_PARAM_DATALINK_DES D ON R.DL_KEY = D.DL_KEY    LEFT JOIN NR_PARAM_DATAREGION DR ON DR.DR_KEY = R.DL_REGION_KEY    LEFT JOIN NR_PARAM_FORM F ON DR.DR_FORM_KEY = F.FM_KEY    WHERE F.FM_FORMSCHEME = ? AND (D.DL_KEY IS NULL OR D.DL_UPDATETIME <> R.DL_UPDATETIME) ) T)", "", "\u5220\u9664\u94fe\u63a5"),
        INSERT_LINK_BLOB("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON D.BD_KEY = R.BD_KEY AND D.BD_CODE = R.BD_CODE AND R.BD_LANG = D.BD_LANG LEFT JOIN NR_PARAM_DATALINK_DES L ON D.BD_KEY = L.DL_KEY LEFT JOIN NR_PARAM_DATAREGION_DES DR ON DR.DR_KEY = L.DL_REGION_KEY LEFT JOIN NR_PARAM_FORM_DES F ON F.FM_KEY = DR.DR_FORM_KEY WHERE F.FM_FORMSCHEME = ? AND D.BD_CODE = 'ATTACHMENT' AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u94fe\u63a5\u4e8c\u8fdb\u5236"),
        INSERT_LINK("INSERT INTO NR_PARAM_DATALINK SELECT D.* FROM NR_PARAM_DATALINK_DES D LEFT JOIN NR_PARAM_DATALINK R ON D.DL_KEY = R.DL_KEY LEFT JOIN NR_PARAM_DATAREGION_DES DR ON D.DL_REGION_KEY = DR.DR_KEY LEFT JOIN NR_PARAM_FORM_DES F ON DR.DR_FORM_KEY = F.FM_KEY WHERE F.FM_FORMSCHEME = ? AND R.DL_KEY IS NULL", "", "\u65b0\u589e\u94fe\u63a5"),
        DELETE_LINK_MAPPING("DELETE FROM NR_PARAM_DATALINKMAPPING WHERE FM_KEY IN (SELECT F.FM_KEY FROM NR_PARAM_FORM F WHERE F.FM_FORMSCHEME = ?)", "", "\u5220\u9664\u5173\u8054\u679a\u4e3e"),
        INSERT_LINK_MAPPING("INSERT INTO NR_PARAM_DATALINKMAPPING SELECT M.* FROM NR_PARAM_DATALINKMAPPING_DES M LEFT JOIN NR_PARAM_FORM_DES F ON M.FM_KEY = F.FM_KEY WHERE F.FM_FORMSCHEME = ?", "", "\u65b0\u589e\u5173\u8054\u679a\u4e3e"),
        DELETE_REGION_SETTING_BLOB("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_CODE IN ('REGION_TAB', 'REGION_ORDER', 'BIG_REGION_CARD', 'REGION_LT_ROW_STYLES', 'REGION_LT_COLUMN_STYLES') AND BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON R.BD_KEY = D.BD_KEY AND R.BD_CODE = D.BD_CODE AND R.BD_LANG = D.BD_LANG    LEFT JOIN NR_PARAM_DATAREGION DR ON DR.DR_REGION_SETTING = R.BD_KEY    LEFT JOIN NR_PARAM_FORM F ON DR.DR_FORM_KEY = F.FM_KEY    WHERE F.FM_FORMSCHEME = ? AND R.BD_CODE IN ('REGION_TAB', 'REGION_ORDER', 'BIG_REGION_CARD', 'REGION_LT_ROW_STYLES', 'REGION_LT_COLUMN_STYLES') AND (D.BD_KEY IS NULL OR R.BD_UPDATETIME <> D.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u533a\u57df\u8bbe\u7f6e\u4e8c\u8fdb\u5236"),
        DELETE_REGION_SETTING("DELETE FROM NR_PARAM_REGIONSETTING WHERE RS_KEY IN ( SELECT RS_KEY FROM (    SELECT R.RS_KEY FROM NR_PARAM_REGIONSETTING R    LEFT JOIN NR_PARAM_REGIONSETTING_DES D ON R.RS_KEY = D.RS_KEY    LEFT JOIN NR_PARAM_DATAREGION DR ON DR.DR_REGION_SETTING = R.RS_KEY    LEFT JOIN NR_PARAM_FORM F ON DR.DR_FORM_KEY = F.FM_KEY    WHERE F.FM_FORMSCHEME = ? AND (D.RS_KEY IS NULL OR R.RS_UPDATETIME <> D.RS_UPDATETIME) ) T)", "", "\u5220\u9664\u533a\u57df\u8bbe\u7f6e"),
        DELETE_REGION("DELETE FROM NR_PARAM_DATAREGION WHERE DR_KEY IN ( SELECT DR_KEY FROM (    SELECT R.DR_KEY FROM NR_PARAM_DATAREGION R    LEFT JOIN NR_PARAM_DATAREGION_DES D ON R.DR_KEY = D.DR_KEY    LEFT JOIN NR_PARAM_FORM F ON R.DR_FORM_KEY = F.FM_KEY    WHERE F.FM_FORMSCHEME = ? AND (D.DR_KEY IS NULL OR R.DR_UPDATETIME <> D.DR_UPDATETIME) ) T)", "", "\u5220\u9664\u533a\u57df"),
        INSERT_REGION_SETTING_BLOB("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON D.BD_KEY = R.BD_KEY AND D.BD_CODE = R.BD_CODE AND R.BD_LANG = D.BD_LANG LEFT JOIN NR_PARAM_DATAREGION_DES DR ON D.BD_KEY = DR.DR_REGION_SETTING LEFT JOIN NR_PARAM_FORM_DES F ON DR.DR_FORM_KEY = F.FM_KEY WHERE F.FM_FORMSCHEME = ? AND D.BD_CODE IN ('REGION_TAB', 'REGION_ORDER', 'BIG_REGION_CARD', 'REGION_LT_ROW_STYLES', 'REGION_LT_COLUMN_STYLES') AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u533a\u57df\u8bbe\u7f6e\u4e8c\u8fdb\u5236"),
        INSERT_REGION_SETTING("INSERT INTO NR_PARAM_REGIONSETTING SELECT D.* FROM NR_PARAM_REGIONSETTING_DES D LEFT JOIN NR_PARAM_REGIONSETTING R ON D.RS_KEY = R.RS_KEY LEFT JOIN NR_PARAM_DATAREGION_DES DR ON D.RS_KEY = DR.DR_REGION_SETTING LEFT JOIN NR_PARAM_FORM_DES F ON DR.DR_FORM_KEY = F.FM_KEY WHERE F.FM_FORMSCHEME = ? AND R.RS_KEY IS NULL", "", "\u65b0\u589e\u533a\u57df\u8bbe\u7f6e"),
        INSERT_REGION("INSERT INTO NR_PARAM_DATAREGION SELECT D.* FROM NR_PARAM_DATAREGION_DES D LEFT JOIN NR_PARAM_DATAREGION R ON R.DR_KEY = D.DR_KEY LEFT JOIN NR_PARAM_FORM_DES F ON D.DR_FORM_KEY = F.FM_KEY WHERE F.FM_FORMSCHEME = ? AND R.DR_KEY IS NULL", "", "\u65b0\u589e\u533a\u57df\u8bbe\u7f6e"),
        DELETE_FORM_BLOB("DELETE FROM NR_PARAM_BIGDATATABLE WHERE BD_CODE IN ('FORM_DATA', 'FILLING_GUIDE', 'BIG_SURVEY_DATA', 'BIG_SCRIPT_EDITOR') AND BD_KEY IN ( SELECT BD_KEY FROM (    SELECT R.BD_KEY FROM NR_PARAM_BIGDATATABLE R    LEFT JOIN NR_PARAM_BIGDATATABLE_DES D ON D.BD_KEY = R.BD_KEY AND D.BD_CODE = R.BD_CODE AND R.BD_LANG = D.BD_LANG    LEFT JOIN NR_PARAM_FORM_DES F ON R.BD_KEY = F.FM_KEY    WHERE F.FM_FORMSCHEME = ? AND R.BD_CODE IN ('FORM_DATA', 'FILLING_GUIDE', 'BIG_SURVEY_DATA', 'BIG_SCRIPT_EDITOR') AND (D.BD_KEY IS NULL OR D.BD_UPDATETIME <> R.BD_UPDATETIME) ) T)", "", "\u5220\u9664\u62a5\u8868\u4e8c\u8fdb\u5236"),
        DELETE_FORM("DELETE FROM NR_PARAM_FORM WHERE FM_KEY IN ( SELECT FM_KEY FROM (     SELECT R.FM_KEY FROM NR_PARAM_FORM R     LEFT JOIN NR_PARAM_FORM_DES D ON R.FM_KEY = D.FM_KEY     WHERE R.FM_FORMSCHEME = ? AND (D.FM_KEY IS NULL OR R.FM_UPDATETIME <> D.FM_UPDATETIME) ) T)", "", "\u5220\u9664\u62a5\u8868"),
        INSERT_FORM_BLOB("INSERT INTO NR_PARAM_BIGDATATABLE SELECT D.* FROM NR_PARAM_BIGDATATABLE_DES D LEFT JOIN NR_PARAM_BIGDATATABLE R ON D.BD_KEY = R.BD_KEY AND D.BD_CODE = R.BD_CODE AND R.BD_LANG = D.BD_LANG LEFT JOIN NR_PARAM_FORM_DES F ON D.BD_KEY = F.FM_KEY WHERE F.FM_FORMSCHEME = ? AND D.BD_CODE IN ('FORM_DATA', 'FILLING_GUIDE', 'BIG_SURVEY_DATA', 'BIG_SCRIPT_EDITOR') AND R.BD_KEY IS NULL", "", "\u65b0\u589e\u62a5\u8868\u4e8c\u8fdb\u5236"),
        INSERT_FORM("INSERT INTO NR_PARAM_FORM SELECT D.* FROM NR_PARAM_FORM_DES D LEFT JOIN NR_PARAM_FORM R ON D.FM_KEY = R.FM_KEY WHERE D.FM_FORMSCHEME = ? AND R.FM_KEY IS NULL", "", "\u65b0\u589e\u62a5\u8868"),
        DELETE_GROUP_LINK("DELETE FROM NR_PARAM_FORMGROUPLINK WHERE FGL_GROUP_KEY IN ( SELECT FGL_GROUP_KEY FROM (    SELECT R.FGL_GROUP_KEY FROM NR_PARAM_FORMGROUPLINK R    LEFT JOIN NR_PARAM_FORMGROUPLINK_DES D ON R.FGL_GROUP_KEY = D.FGL_GROUP_KEY AND R.FGL_FORM_KEY = D.FGL_FORM_KEY    LEFT JOIN NR_PARAM_FORMGROUP G ON G.FG_KEY = R.FGL_GROUP_KEY    WHERE G.FG_FORM_SCHEME_KEY = ? AND (D.FGL_GROUP_KEY IS NULL OR R.FGL_UPDATETIME <> D.FGL_UPDATETIME) ) T)", "", "\u5220\u9664\u62a5\u8868\u5206\u7ec4\u94fe\u63a5"),
        DELETE_GROUP("DELETE FROM NR_PARAM_FORMGROUP WHERE FG_KEY IN ( SELECT FG_KEY FROM (     SELECT R.FG_KEY FROM NR_PARAM_FORMGROUP R     LEFT JOIN NR_PARAM_FORMGROUP_DES D ON R.FG_KEY = D.FG_KEY     WHERE R.FG_FORM_SCHEME_KEY = ? AND (D.FG_KEY IS NULL OR R.FG_UPDATETIME <> D.FG_UPDATETIME) ) T)", "", "\u5220\u9664\u62a5\u8868\u5206\u7ec4"),
        INSERT_GROUP_LINK("INSERT INTO NR_PARAM_FORMGROUPLINK SELECT D.* FROM NR_PARAM_FORMGROUPLINK_DES D LEFT JOIN NR_PARAM_FORMGROUPLINK R ON D.FGL_GROUP_KEY = R.FGL_GROUP_KEY AND D.FGL_FORM_KEY = R.FGL_FORM_KEY LEFT JOIN NR_PARAM_FORMGROUP_DES G ON D.FGL_GROUP_KEY = G.FG_KEY WHERE G.FG_FORM_SCHEME_KEY = ? AND R.FGL_GROUP_KEY IS NULL", "", "\u65b0\u589e\u62a5\u8868\u5206\u7ec4\u94fe\u63a5"),
        INSERT_GROUP("INSERT INTO NR_PARAM_FORMGROUP SELECT D.* FROM NR_PARAM_FORMGROUP_DES D LEFT JOIN NR_PARAM_FORMGROUP R ON D.FG_KEY = R.FG_KEY WHERE D.FG_FORM_SCHEME_KEY = ? AND R.FG_KEY IS NULL", "", "\u65b0\u589e\u62a5\u8868\u5206\u7ec4"),
        DELETE_SCHEME_LINK_ORG_MAPPING("DELETE FROM NR_PARAM_TASKLINK_ORG where TOR_TR_KEY in ( SELECT TOR_TR_KEY FROM (    SELECT TOR.TOR_TR_KEY FROM NR_PARAM_TASKLINK_ORG TOR    LEFT JOIN NR_PARAM_TASKLINK_DES TR ON TOR_TR_KEY = TR.TR_KEY    WHERE TR.TR_CURRENT_FORM_SCHEME_KEY = ? )T)", "", "\u5220\u9664\u5173\u8054\u4efb\u52a1-\u5b9e\u4f53\u5bf9\u5e94\u89c4\u5219"),
        INSERT_SCHEME_LINK_ORG_MAPPING("INSERT INTO  NR_PARAM_TASKLINK_ORG SELECT TOR.* FROM NR_PARAM_TASKLINK_ORG_DES TOR LEFT JOIN NR_PARAM_TASKLINK_DES TR ON TOR_TR_KEY = TR.TR_KEY WHERE TR.TR_CURRENT_FORM_SCHEME_KEY = ? ", "", "\u65b0\u589e\u5173\u8054\u4efb\u52a1-\u5b9e\u4f53\u5bf9\u5e94\u89c4\u5219"),
        DELETE_SCHEME_LINK("DELETE FROM NR_PARAM_TASKLINK WHERE TR_CURRENT_FORM_SCHEME_KEY = ?", "", "\u5220\u9664\u5173\u8054\u4efb\u52a1"),
        INSERT_SCHEME_LINK("INSERT INTO NR_PARAM_TASKLINK SELECT * FROM NR_PARAM_TASKLINK_DES WHERE TR_CURRENT_FORM_SCHEME_KEY = ?", "", "\u65b0\u589e\u5173\u8054\u4efb\u52a1"),
        DELETE_SCHEME("DELETE FROM NR_PARAM_FORMSCHEME WHERE FC_KEY IN ( SELECT FC_KEY FROM (    SELECT R.FC_KEY FROM NR_PARAM_FORMSCHEME R    LEFT JOIN NR_PARAM_FORMSCHEME_DES D ON R.FC_KEY = D.FC_KEY    WHERE R.FC_KEY = ? AND (D.FC_KEY IS NULL OR R.FC_UPDATETIME <> D.FC_UPDATETIME) ) T)", "", "\u5220\u9664\u62a5\u8868\u65b9\u6848"),
        INSERT_SCHEME("INSERT INTO NR_PARAM_FORMSCHEME SELECT D.* FROM NR_PARAM_FORMSCHEME_DES D LEFT JOIN NR_PARAM_FORMSCHEME R ON D.FC_KEY = R.FC_KEY WHERE D.FC_KEY = ? AND R.FC_KEY IS NULL", "", "\u65b0\u589e\u62a5\u8868\u65b9\u6848");

        private final String deploy;
        private final String rollback;
        private final String desc;

        private FormScheme(String deploy, String rollback, String desc) {
            this.deploy = deploy;
            this.rollback = rollback;
            this.desc = desc;
        }

        @Override
        public String getDeploySQL() {
            return this.deploy;
        }

        @Override
        public String getRollbackSQL() {
            return this.rollback;
        }

        @Override
        public String getDescription() {
            return this.desc;
        }
    }
}

