/*
 * Decompiled with CFR 0.152.
 */
package com.jiuqi.dc.mappingscheme.client.common;

public interface DataRefConst {
    public static final String ODS_TABLENAME_TEMPLATE = "ODS_%1$s_%2$s";
    public static final String ODS_PREFIX_TEMPLATE = "ODS_%1$s";
    public static final String ODS_PREFIX = "ODS";
    public static final String REF_TABLENAME_TEMPLATE = "REF_%1$s";
    public static final String FN_NODE_LABEL = "%1$s %2$s";
    public static final String TBDC_DATASCHEME = "DC_REF_DATASCHEME";
    public static final String DC_SCHEME_DATAMAPPING = "DC_SCHEME_DATAMAPPING";
    public static final String DC_SCHEME_DATAMAPPINGOPTION = "DC_SCHEME_DATAMAPPINGOPTION";
    public static final String TBDC_DATAMAPINGDFINE = "DC_REF_DATAMAPINGDFINE";
    public static final String TBDC_FIELDMAPINGDFINE = "DC_REF_FIELDMAPINGDFINE";
    public static final String TBDC_DATASCHEMEOPTION = "DC_REF_DATASCHEMEOPTION";
    public static final String FD_DATASOURCECODE = "DATASOURCECODE";
    public static final String FD_SOURCEDATATYPE = "SOURCEDATATYPE";
    public static final String FD_ETLJOBID = "ETLJOBID";
    public static final String FD_DATAMAPPING = "DATAMAPPING";
    public static final String FD_PLUGINTYPE = "PLUGINTYPE";
    public static final String FD_ORGMAPPINGTYPE = "ORGMAPPINGTYPE";
    public static final String FD_CUSTOMCONFIG = "CUSTOMCONFIG";
    public static final String FD_DATASCHEMECODE = "DATASCHEMECODE";
    public static final String FD_TABLENAME = "TABLENAME";
    public static final String FD_TABLETITLE = "TABLETITLE";
    public static final String FD_MODELTYPE = "MODELTYPE";
    public static final String FD_ODS_TABLENAME = "ODS_TABLENAME";
    public static final String FD_AUTOMATCHDIM = "AUTOMATCHDIM";
    public static final String FD_ADVANCEDSQL = "ADVANCEDSQL";
    public static final String FD_DATAMAPPINGID = "DATAMAPPINGID";
    public static final String FD_FIELDNAME = "FIELDNAME";
    public static final String FD_FIELDTITLE = "FIELDTITLE";
    public static final String FD_STORAGETYPE = "STORAGETYPE";
    public static final String FD_FIELDSOURCETYPE = "FIELDSOURCETYPE";
    public static final String FD_FIELDMAPPINGTYPE = "FIELDMAPPINGTYPE";
    public static final String FD_ODS_FIELDNAME = "ODS_FIELDNAME";
    public static final String FD_RULETYPE = "RULETYPE";
    public static final String FD_FIXEDFLAG = "FIXEDFLAG";
    public static final String FD_ALIGNMENT = "ALIGNMENT";
    public static final String FD_VISIABLE = "VISIABLE";
    public static final String FD_ORDINAL = "ORDINAL";
    public static final String FD_SORTABLE = "SORTABLE";
    public static final String FD_SORTORDER = "SORTORDER";
    public static final String FD_SORTASC = "SORTASC";
    public static final String FD_ODS_ID = "ODS_ID";
    public static final String FD_ODS_CODE = "ODS_CODE";
    public static final String FD_ODS_NAME = "ODS_NAME";
    public static final String FD_ODS_UNITCODE = "ODS_UNITCODE";
    public static final String FD_AUTOMATCHFLAG = "AUTOMATCHFLAG";
    public static final String FN_IDX = "IDX";
    public static final String FN_IGNORED = "IGNORED";
    public static final String FN_MATCHED = "MATCHED";
    public static final String FD_HANDLESTATUS = "HANDLESTATUS";
    public static final String FD_OPERATOR = "OPERATOR";
    public static final String FD_OPERATETIME = "OPERATETIME";
    public static final String FD_STARTTIME = "STARTTIME";
    public static final String FD_ENDTIME = "ENDTIME";
    public static final String IDX_DS_TEMPLATE = "I_%1$s_DS";
    public static final String IDX_FIELD_TEMPLATE = "I_%1$s_%2$s";
    public static final String IDX_FIELD_ODS_ID = "OI";
    public static final String IDX_FIELD_ODS_CODE = "OC";
    public static final String IDX_FIELD_CODE = "C";
    public static final String FN_CODE_LABEL = "\u4ee3\u7801";
    public static final String FD_REMARK = "REMARK";
    public static final String FN_REMARK = "\u5907\u6ce8";
    public static final String FD_UNIT_EXT_DIM_CODE = "ODS_ASSISTCODE";
    public static final String FN_UNIT_EXT_DIM_CODE = "\u5355\u4f4d\u6269\u5c55\u7ef4\u5ea6\u4ee3\u7801";
    public static final String FD_UNIT_EXT_DIM_NAME = "ODS_ASSISTNAME";
    public static final String FN_UNIT_EXT_DIM_NAME = "\u5355\u4f4d\u6269\u5c55\u7ef4\u5ea6\u540d\u79f0";
    public static final String FD_UNITCODE = "ODS_UNITCODE";
    public static final String FN_UNITCODE = "\u7ec4\u7ec7\u673a\u6784";
    public static final String FD_DC_UNITCODE = "DC_UNITCODE";
    public static final String FD_DC_UNITNAME = "DC_UNITNAME";
    public static final String FD_ALIAS_DC_UNITCODE = "UNITCODE";
    public static final String FD_REAL_UNITCODE = "REAL_UNITCODE";
    public static final String FN_DC_UNITCODE = "\u4e00\u672c\u8d26\u7ec4\u7ec7\u673a\u6784";
    public static final String FD_BOOKCODE = "ODS_BOOKCODE";
    public static final String FN_BOOKCODE = "\u8d26\u7c3f";
    public static final String FD_ACCTYEAR = "ODS_ACCTYEAR";
    public static final String FN_ACCTYEAR = "\u5e74\u5ea6";
    public static final String FD_CUSTOM = "ODS_CUSTOM_CODE";
    public static final String FN_CUSTOM = "\u81ea\u5b9a\u4e49\u4ee3\u7801";
    public static final String SHARE_SIGN = "-";
}

