/*
 * Decompiled with CFR 0.152.
 */
package com.jiuqi.nr.common.constant;

import java.util.HashMap;

public enum AsynctaskPoolType {
    ASYNCTASK_BATCHCLEAR(101, "ASYNCTASK_BATCHCLEAR"),
    ASYNCTASK_BATCHCOPY(102, "ASYNCTASK_BATCHCOPY"),
    ASYNCTASK_EFDC(103, "ASYNCTASK_EFDC"),
    ASYNCTASK_BATCHEFDC(110, "ASYNCTASK_BATCHEFDC"),
    ASYNCTASK_BATCHDATASUM(104, "ASYNCTASK_BATCHDATASUM"),
    ASYNCTASK_NODECHECK(105, "ASYNCTASK_NODECHECK"),
    ASYNCTASK_BATCHNODECHECK(109, "ASYNCTASK_BATCHNODECHECK"),
    ASYNCTASK_BATCHEXPORT(106, "ASYNCTASK_BATCHEXPORT"),
    ASYNCTASK_BATCHIMPORT(107, "ASYNCTASK_BATCHIMPORT"),
    ASYNCTASK_UPLOADFILE(108, "ASYNCTASK_UPLOADFILE"),
    ASYNCTASK_BATCHDATAPUBLISH(109, "ASYNCTASK_BATCHDATAPUBLISH"),
    ASYNCTASK_ETL(119, "ASYNCTASK_ETL"),
    ASYNCTASK_STARTPROCESS(110, "ASYNCTASK_STARTPROCESS"),
    ASYNCTASK_STOPPROCESS(111, "ASYNCTASK_STOPPROCESS"),
    ASYNCTASK_UNBINDPROCESS(112, "ASYNCTASK_UNBINDPROCESS"),
    ASYNCTASK_BATCHCALCULATE(201, "ASYNCTASK_BATCHCALCULATE"),
    ASYNCTASK_BATCHCHECK(202, "ASYNCTASK_BATCHCHECK"),
    ASYNCTASK_ALLCALCULATE(203, "ASYNCTASK_ALLCALCULATE"),
    ASYNCTASK_ALLCHECK(204, "ASYNCTASK_ALLCHECK"),
    ASYNCTASK_BATCHCHECKANALYSISFORM(205, "ASYNCTASK_BATCHCHECKANALYSISFORM"),
    ASYNCTASK_BATCHPRINT(301, "ASYNCTASK_BATCHPRINT"),
    ASYNCTASK_BATCHUPLOAD(302, "ASYNCTASK_BATCHUPLOAD"),
    ASYNCTASK_PARAMEXPORT(303, "ASYNCTASK_PARAMEXPORT"),
    ASYNCTASK_PARAMIMPORT(304, "ASYNCTASK_PARAMIMPORT"),
    ASYNCTASK_WORKFLOWEXE(305, "ASYNCTASK_WORKFLOWEXE"),
    ASYNCTASK_COMPILATION_FL(306, "ASYNCTASK_COMPILATION_FL"),
    ASYNCTASK_DELETETASK(307, "ASYNCTASK_DELETETASK"),
    ASYNCTASK_PARAMEXAMIE(308, "ASYNCTASK_PARAMEXAMINE"),
    ASYNCTASK_PARAMRESTORE(309, "ASYNCTASK_PARAMRESTORE"),
    ASYNCTASK_SINGLEIMPORT(310, "ASYNCTASK_SINGLEIMPORT"),
    ASYNCTASK_TASKDATACOPY(311, "ASYNCTASK_TASKDATACOPY"),
    ASYNCTASK_SINGLESPLIT(312, "ASYNCTASK_SINGLESPLIT"),
    ASYNCTASK_ANALYSISPARAM_EXPORT(401, "ASYNCTASK_ANALYSISPARAM_EXPORT"),
    ASYNCTASK_ANALYSISPARAM_IMPORT(402, "ASYNCTASK_ANALYSISPARAM_IMPORT"),
    ASYNCTASK_ANALYSIS_BATCHANALYSIS(403, "ASYNCTASK_ANALYSIS_BATCHANALYSIS"),
    ASYNCTASK_BATCH_FORM_LOCK(501, "ASYNCTASK_BATCH_FORM_LOCK"),
    ASYNCTASK_ROLLBACK_ACCOUNT_DATA(502, "ASYNCTASK_ROLLBACK_ACCOUNT_DATA"),
    ASYNCTASK_MIDSTORE_BATCH(601, "ASYNCTASK_MIDSTORE_BATCH"),
    ASYNCTASK_MIDSTORE_GETDATA(602, "ASYNCTASK_MIDSTORE_GETDATA"),
    ASYNCTASK_MIDSTORE_POSTDATA(603, "ASYNCTASK_MIDSTORE_POSTDATA");

    private int typeValue;
    private String typeName;
    private static HashMap<Integer, AsynctaskPoolType> mappings;

    private static synchronized HashMap<Integer, AsynctaskPoolType> getMappings() {
        if (mappings == null) {
            mappings = new HashMap();
        }
        return mappings;
    }

    private AsynctaskPoolType(int value, String name) {
        this.typeValue = value;
        this.typeName = name;
        AsynctaskPoolType.getMappings().put(value, this);
    }

    public int getValue() {
        return this.typeValue;
    }

    public String getName() {
        return this.typeName;
    }

    public static AsynctaskPoolType forValue(int value) {
        return AsynctaskPoolType.getMappings().get(value);
    }
}

