/*
 * Decompiled with CFR 0.152.
 */
package com.jiuqi.nr.fmdm.service;

import java.util.List;
import java.util.Map;

public interface IBBLXDataDetermineService {
    public boolean needAutoGenerate(Map<String, Object> var1, String var2);

    public List<Boolean> filterUnAutoGenerateData(List<Map<String, Object>> var1, String var2);
}

