/*
 * Decompiled with CFR 0.152.
 */
package com.jiuqi.np.period;

import com.jiuqi.np.period.PeriodModifier;
import java.util.Hashtable;

class ReservedModifierManager {
    static Hashtable MODIFIERs = new Hashtable();
    static Hashtable<String, String> MODIFIER_TITILS = new Hashtable();

    ReservedModifierManager() {
    }

    static {
        PeriodModifier modifier = new PeriodModifier();
        modifier.periodType = 1;
        MODIFIERs.put("\u5e74", modifier);
        MODIFIERs.put("\u5e74\u5ea6", modifier);
        MODIFIERs.put("N", modifier);
        MODIFIERs.put("n", modifier);
        MODIFIER_TITILS.put("N", "\u5e74");
        modifier = new PeriodModifier();
        modifier.yearModifier = -1;
        MODIFIERs.put("\u53bb\u5e74", modifier);
        MODIFIERs.put("-1N", modifier);
        MODIFIERs.put("-1n", modifier);
        MODIFIER_TITILS.put("-1N", "\u53bb\u5e74");
        MODIFIER_TITILS.put("-1J", "\u4e0a\u4e00\u5b63");
        modifier = new PeriodModifier();
        modifier.yearModifier = -1;
        MODIFIERs.put("\u53bb\u5e74", modifier);
        MODIFIERs.put("-1N", modifier);
        MODIFIERs.put("-1n", modifier);
        modifier = new PeriodModifier();
        modifier.yearModifier = -2;
        MODIFIERs.put("\u524d\u5e74", modifier);
        MODIFIER_TITILS.put("-2N", "\u524d\u5e74");
        modifier = new PeriodModifier();
        modifier.yearModifier = 1;
        MODIFIERs.put("\u660e\u5e74", modifier);
        MODIFIERs.put("+1N", modifier);
        MODIFIERs.put("+1n", modifier);
        MODIFIER_TITILS.put("+1N", "\u660e\u5e74");
        modifier = new PeriodModifier();
        modifier.periodModifier = -1;
        modifier.periodType = 4;
        MODIFIERs.put("-1Y", modifier);
        MODIFIERs.put("-1y", modifier);
        MODIFIER_TITILS.put("-1Y", "\u4e0a\u6708");
        modifier = new PeriodModifier();
        modifier.periodModifier = -1;
        MODIFIERs.put("\u4e0a\u671f", modifier);
        MODIFIERs.put("\u4e0a\u4e00\u671f", modifier);
        MODIFIERs.put("\u524d\u4e00\u671f", modifier);
        modifier = new PeriodModifier();
        modifier.periodModifier = 1;
        MODIFIERs.put("\u4e0b\u671f", modifier);
        MODIFIERs.put("\u4e0b\u4e00\u671f", modifier);
        MODIFIERs.put("\u540e\u4e00\u671f", modifier);
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 2;
        modifier.periodModifier = 1;
        MODIFIERs.put("1H", modifier);
        MODIFIERs.put("1h", modifier);
        MODIFIERs.put("\u4e0a\u534a\u5e74", modifier);
        MODIFIER_TITILS.put("1H", "\u4e0a\u534a\u5e74");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 2;
        modifier.periodModifier = 2;
        MODIFIERs.put("2H", modifier);
        MODIFIERs.put("2h", modifier);
        MODIFIERs.put("\u4e0b\u534a\u5e74", modifier);
        MODIFIER_TITILS.put("2H", "\u4e0b\u534a\u5e74");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 3;
        modifier.periodModifier = 1;
        MODIFIERs.put("1J", modifier);
        MODIFIERs.put("1j", modifier);
        MODIFIERs.put("\u4e00\u5b63\u5ea6", modifier);
        MODIFIERs.put("\u7b2c\u4e00\u5b63\u5ea6", modifier);
        MODIFIER_TITILS.put("1J", "\u4e00\u5b63\u5ea6");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 3;
        modifier.periodModifier = 2;
        MODIFIERs.put("2J", modifier);
        MODIFIERs.put("2j", modifier);
        MODIFIERs.put("\u4e8c\u5b63\u5ea6", modifier);
        MODIFIERs.put("\u7b2c\u4e8c\u5b63\u5ea6", modifier);
        MODIFIER_TITILS.put("2J", "\u4e8c\u5b63\u5ea6");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 3;
        modifier.periodModifier = 3;
        MODIFIERs.put("3J", modifier);
        MODIFIERs.put("3j", modifier);
        MODIFIERs.put("\u4e09\u5b63\u5ea6", modifier);
        MODIFIERs.put("\u7b2c\u4e09\u5b63\u5ea6", modifier);
        MODIFIER_TITILS.put("3J", "\u4e09\u5b63\u5ea6");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 3;
        modifier.periodModifier = 4;
        MODIFIERs.put("4J", modifier);
        MODIFIERs.put("4j", modifier);
        MODIFIERs.put("\u56db\u5b63\u5ea6", modifier);
        MODIFIERs.put("\u7b2c\u56db\u5b63\u5ea6", modifier);
        MODIFIER_TITILS.put("4J", "\u56db\u5b63\u5ea6");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 1;
        MODIFIERs.put("1Y", modifier);
        MODIFIERs.put("1y", modifier);
        MODIFIERs.put("\u4e00\u6708", modifier);
        MODIFIERs.put("\u7b2c\u4e00\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("1Y", "\u4e00\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 2;
        MODIFIERs.put("2Y", modifier);
        MODIFIERs.put("2y", modifier);
        MODIFIERs.put("\u4e8c\u6708", modifier);
        MODIFIERs.put("\u7b2c\u4e8c\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("2Y", "\u4e8c\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 3;
        MODIFIERs.put("3Y", modifier);
        MODIFIERs.put("3y", modifier);
        MODIFIERs.put("\u4e09\u6708", modifier);
        MODIFIERs.put("\u7b2c\u4e09\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("3Y", "\u4e09\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 4;
        MODIFIERs.put("4Y", modifier);
        MODIFIERs.put("4y", modifier);
        MODIFIERs.put("\u56db\u6708", modifier);
        MODIFIERs.put("\u7b2c\u56db\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("4Y", "\u56db\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 5;
        MODIFIERs.put("5Y", modifier);
        MODIFIERs.put("5y", modifier);
        MODIFIERs.put("\u4e94\u6708", modifier);
        MODIFIERs.put("\u7b2c\u4e94\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("5Y", "\u4e94\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 6;
        MODIFIERs.put("6Y", modifier);
        MODIFIERs.put("6y", modifier);
        MODIFIERs.put("\u516d\u6708", modifier);
        MODIFIERs.put("\u7b2c\u516d\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("6Y", "\u516d\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 7;
        MODIFIERs.put("7Y", modifier);
        MODIFIERs.put("7y", modifier);
        MODIFIERs.put("\u4e03\u6708", modifier);
        MODIFIERs.put("\u7b2c\u4e03\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("7Y", "\u4e03\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 8;
        MODIFIERs.put("8Y", modifier);
        MODIFIERs.put("8y", modifier);
        MODIFIERs.put("\u516b\u6708", modifier);
        MODIFIERs.put("\u7b2c\u516b\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("8Y", "\u516b\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 9;
        MODIFIERs.put("9Y", modifier);
        MODIFIERs.put("9y", modifier);
        MODIFIERs.put("\u4e5d\u6708", modifier);
        MODIFIERs.put("\u7b2c\u4e5d\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("9Y", "\u4e5d\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 10;
        MODIFIERs.put("10Y", modifier);
        MODIFIERs.put("10y", modifier);
        MODIFIERs.put("\u5341\u6708", modifier);
        MODIFIERs.put("\u7b2c\u5341\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("10Y", "\u5341\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 11;
        MODIFIERs.put("11Y", modifier);
        MODIFIERs.put("11y", modifier);
        MODIFIERs.put("\u5341\u4e00\u6708", modifier);
        MODIFIERs.put("\u7b2c\u5341\u4e00\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("11Y", "\u5341\u4e00\u6708");
        modifier = new PeriodModifier();
        modifier.periodFlag = 1;
        modifier.periodType = 4;
        modifier.periodModifier = 12;
        MODIFIERs.put("12Y", modifier);
        MODIFIERs.put("12y", modifier);
        MODIFIERs.put("\u5341\u4e8c\u6708", modifier);
        MODIFIERs.put("\u7b2c\u5341\u4e8c\u6708\u4efd", modifier);
        MODIFIER_TITILS.put("12Y", "\u5341\u4e8c\u6708");
    }
}

