/*
 * Decompiled with CFR 0.152.
 */
package com.jiuqi.dc.base.impl.option;

public enum DcSysOptionIdEnum {
    DC_ADJUSTVOUCHER_MOUTH,
    DC_ADJUSTVOUCHER_QUARTERLY,
    DC_ADJUSTVOUCHER_HALFYEAR,
    DC_ADJUSTVOUCHER_YEAR,
    DC_ADJUSTVOUCHER_DIGESTNOTNULL,
    DC_ADJUSTVOUCHER_BIZDATEENABLE,
    DC_ADJUSTVOUCHER_CFITEMENABLE,
    DC_ADJUSTVOUCHER_ENABLE_ORGNCURR,
    DC_ADJUSTVOUCHER_REMARKENABLE,
    DC_BALANCE_CONVERSION_ENABLE,
    DC_BALANCE_ORGN_ENABLE,
    DC_BALACEREBUILD_ENABLECHECK,
    DC_BALACEREBUILD_INCLUDETRANSFERVCHR,
    DC_BALANCEREBUILD_CLOSE,
    JDBC_SQL_RECORD,
    DC_EQUITYSUBJINIT,
    DC_RECLASSIFY_ENABLE,
    DC_RECLASSIFY_TRIGGER_DATA_CHANGE_ENABLE,
    DC_ETL_VCHR_FIELD_ENABLE,
    DC_ETL_AFTER_VCHR_ENABLE,
    DC_VCHR_DIM_SHOW_TYPE;

}

