/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.jiuqi.nr.datascheme.api.DataGroup
 *  com.jiuqi.nr.datascheme.api.type.DataGroupKind
 */
package com.jiuqi.nr.datascheme.common;

import com.jiuqi.nr.datascheme.api.DataGroup;
import com.jiuqi.nr.datascheme.api.type.DataGroupKind;
import com.jiuqi.nr.datascheme.internal.dto.DataGroupDTO;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Consts {
    public static final Logger NR_PARAM_GRAPH_LOGGER = LoggerFactory.getLogger("com.jiuqi.nr.definition.cache");
    public static final String FIELD_OPTION_GROUP_ID = "field-group";
    public static final String FIELD_OPTION_AUTHORITY_ID = "Field_AUTHORITY";
    public static final String AMOUNT = "9493b4eb-6516-48a8-a878-25a63a23e63a;";
    public static final String SPLIT_CHAR = ";";
    public static final String FIELD_NAME_SPLIT_CHAR = "_";
    public static final String MEASURE_UNIT_EMPTY_CHAR = "-";
    public static final String TABLE_CODE_PREFIX_SPLIT_CHAR = "_";
    public static final String REPEAT_CODE_SUFFIX_SPLIT_CHAR = "_";
    public static final String NVWA_CATALOG_ROOT = "10000000-1100-1110-1111-000000000000";
    public static final String DATASCHEME_ROOT_GROUP = "00000000-0000-0000-0000-000000000000";
    public static final String DATASCHEME_ROOT_GROUP_TITLE = "\u5168\u90e8\u6570\u636e\u65b9\u6848";
    public static final String QUERY_DATASCHEME_ROOT_GROUP = "00000000-0000-0000-0000-111111111111";
    public static final String QUERY_DATASCHEME_ROOT_GROUP_TITLE = "\u5168\u90e8\u67e5\u8be2\u6570\u636e\u65b9\u6848";
    @Deprecated
    public static final String COVER_ID = "ID";
    public static final String DATATABLE_DEFAULT_OWNER = "NR";
    public static final String TABLE_MODEL_OWNER = "NR";
    public static final String DB_FIELD_PREFIX = "F_";
    public static final String DB_ORG_FIELD_NAME = "MDCODE";
    public static final String MD_ADJUST = "ADJUST";
    public static final String MD_ADJUST_TITLE = "\u8c03\u6574\u671f";
    public static final String MD_ADJUST_DEFAULT_VALUE = "0";
    public static final String DB_PERIOD_FIELD_NAME = "DATATIME";
    public static final String MD_INFO_SUFFIX = "MD_INFO";
    public static final String MD_INFO_TITLE = "\u5355\u4f4d\u4fe1\u606f";
    public static final String DB_DIM_FIELD_PREFIX = "D_";
    public static final String DB_UNIQUE_INDEX_PREFIX = "UQ_";
    public static final String DB_NORMAL_INDEX_PREFIX = "NM_";
    public static final int DB_UNIQUE_INDEX_NAMELENGTH = 30;
    public static final int DB_FIELD_NAME_MAX_LENGTH = 20;
    public static final String TN_ACCOUNT_RPT_SUFFIX = "_RPT";
    public static final String TN_ACCOUNT_HIS_SUFFIX = "_HIS";
    public static final String TN_ACCOUNT_COL_CODE_VALIDDATATIME = "VALIDDATATIME";
    public static final String TN_ACCOUNT_COL_CODE_INVALIDDATATIME = "INVALIDDATATIME";
    public static final String TN_ACCOUNT_COL_CODE_VALIDTIME = "VALIDTIME";
    public static final String TN_ACCOUNT_COL_CODE_MODIFYTIME = "MODIFYTIME";
    public static final String TN_ACCOUNT_COL_CODE_DIGEST = "DIGEST";
    public static final String DF_BIZKEYORFER_CODE = "BIZKEYORDER";
    public static final String DF_FLOATORFER_CODE = "FLOATORDER";
    public static final String DF_ACCOUNTID_CODE = "SBID";
    public static final String DB_TABLE_SUFFIX = "_DES";
    public static final String DATA_SCHEME = "NR_DATASCHEME_SCHEME";
    public static final String DATA_SCHEME_DES = "NR_DATASCHEME_SCHEME_DES";
    public static final String DS_DDL_STATUS_BIT = "DS_DDL_STATUS_BIT";
    private static final String DATA_SCHEME_PRE = "DS_";
    public static final String DS_KEY = "DS_KEY";
    public static final String DS_CODE = "DS_CODE";
    public static final String DS_TITLE = "DS_TITLE";
    public static final String DS_DESC = "DS_DESC";
    public static final String DS_DATA_GROUP = "DS_DG_KEY";
    public static final String DS_PREFIX = "DS_PREFIX";
    public static final String DS_TYPE = "DS_TYPE";
    public static final String DS_CREATOR = "DS_CREATOR";
    public static final String DS_SHARE_TYPE = "DS_SHARE_TYPE";
    public static final String DS_IS_AUTO = "DS_IS_AUTO";
    public static final String DS_VERSION = "DS_VERSION";
    public static final String DS_LEVEL = "DS_LEVEL";
    public static final String DS_ORDER = "DS_ORDER";
    public static final String DS_UPDATE_TIME = "DS_UPDATE_TIME";
    public static final String DS_DG_KEY = "DS_DG_KEY";
    public static final String DS_BIZCODE = "DS_BIZCODE";
    public static final String DS_GATHER_DB = "DS_GATHER_DB";
    public static final String DS_ENCRYPT_SCENE = "DS_ENCRYPT_SCENE";
    public static final String DS_ZS_KEY = "DS_ZS_KEY";
    public static final String DS_ZS_VERSION = "DS_ZS_VERSION";
    public static final String DS_ANALYSE_ZB = "DS_ANALYSE_ZB";
    public static final String DS_CALIBRE = "DS_CALIBRE";
    public static final String DATA_SCHEME_GROUP = "NR_DATASCHEME_GROUP";
    public static final String DATA_SCHEME_GROUP_DES = "NR_DATASCHEME_GROUP_DES";
    private static final String DATA_SCHEME_GROUP_PRE = "DG_";
    public static final String DG_KEY = "DG_KEY";
    public static final String DG_DS_KEY = "DG_DS_KEY";
    public static final String DG_CODE = "DG_CODE";
    public static final String DG_TITLE = "DG_TITLE";
    public static final String DG_DESC = "DG_DESC";
    public static final String DG_KIND = "DG_KIND";
    public static final String DG_PARENT_KEY = "DG_PARENT_KEY";
    public static final String DG_VERSION = "DG_VERSION";
    public static final String DG_LEVEL = "DG_LEVEL";
    public static final String DG_ORDER = "DG_ORDER";
    public static final String DG_UPDATE_TIME = "DG_UPDATE_TIME";
    public static final String DATA_SCHEME_TABLE_DES = "NR_DATASCHEME_TABLE_DES";
    public static final String DATA_SCHEME_TABLE = "NR_DATASCHEME_TABLE";
    private static final String DATA_SCHEME_TABLE_PRE = "DT_";
    public static final String DT_KEY = "DT_KEY";
    public static final String DT_DS_KEY = "DT_DS_KEY";
    public static final String DT_DG_KEY = "DT_DG_KEY";
    public static final String DT_CODE = "DT_CODE";
    public static final String DT_TITLE = "DT_TITLE";
    public static final String DT_TYPE = "DT_TYPE";
    public static final String DT_DESC = "DT_DESC";
    public static final String DT_BIZ_KEYS = "DT_BIZKEYS";
    public static final String DT_GATHER_FIELD_KEYS = "DT_GATHERFIELDKEYS";
    public static final String DT_GATHER_TYPE = "DT_GATHER_TYPE";
    public static final String DT_VERSION = "DT_VERSION";
    public static final String DT_LEVEL = "DT_LEVEL";
    public static final String DT_ORDER = "DT_ORDER";
    public static final String DT_REPEAT_CODE = "DT_REPEAT_CODE";
    public static final String DT_UPDATE_TIME = "DT_UPDATE_TIME";
    public static final String DT_OWNER = "DT_OWNER";
    public static final String DT_TRACK_HISTORY = "DT_TRACK_HISTORY";
    public static final String DT_SYNC_ERROR = "DT_SYNC_ERROR";
    public static final String DT_EXPRESSION = "DT_EXPRESSION";
    public static final String DT_ALIAS = "DT_ALIAS";
    public static final String DATASCHEME_FIELD_DES = "NR_DATASCHEME_FIELD_DES";
    public static final String DATASCHEME_FIELD = "NR_DATASCHEME_FIELD";
    private static final String DATA_DATASCHEME_FIELD_PRE = "DF_";
    public static final String DF_KEY = "DF_KEY";
    public static final String DF_DS_KEY = "DF_DS_KEY";
    public static final String DF_DT_KEY = "DF_DT_KEY";
    public static final String DF_KIND = "DF_KIND";
    public static final String DF_APPLY_TYPE = "DF_APPLY_TYPE";
    public static final String DF_TITLE = "DF_TITLE";
    public static final String DF_ORDER = "DF_ORDER";
    public static final String DF_VERSION = "DF_VERSION";
    public static final String DF_LEVEL = "DF_LEVEL";
    public static final String DF_UPDATETIME = "DF_UPDATETIME";
    public static final String DF_CODE = "DF_CODE";
    public static final String DF_ALIAS = "DF_ALIAS";
    public static final String DF_DESC = "DF_DESC";
    public static final String DF_DEFAULT = "DF_DEFAULT";
    public static final String DF_PRECISION = "DF_PRECISION";
    public static final String DF_DATATYPE = "DF_DATATYPE";
    public static final String DF_DECIMAL = "DF_DECIMAL";
    public static final String DF_NULLABLE = "DF_NULLABLE";
    public static final String DF_REF_ENTITY_ID = "DF_REF_ENTITY_ID";
    public static final String DF_REF_FIELD_ID = "DF_REF_FIELD_ID";
    public static final String DF_VALIDATION_RULES = "DF_VALIDATION_RULE";
    public static final String DF_MEASUREUNIT = "DF_MEASUREUNIT";
    public static final String DF_AGGRTYPE = "DF_AGGRTYPE";
    public static final String DF_MULTIVAL = "DF_MULTIVAL";
    public static final String DF_ONLY_LEAF = "DF_ONLY_LEAF";
    public static final String DF_SHOWFORMAT = "DF_SHOWFORMAT";
    public static final String DF_SECRET_LEVEL = "DF_SECRET_LEVEL";
    public static final String DF_USEAUTHORITY = "DF_USEAUTHORITY";
    public static final String DF_ALLOW_UNDEFINED_CODE = "DF_ALLOW_UNDEFINED_CODE";
    public static final String DF_CHANGE_WITH_PERIOD = "DF_CHANGE_WITH_PERIOD";
    public static final String DF_GENERATE_VERSION = "DF_GENERATE_VERSION";
    public static final String DF_ALLOW_TREE_SUM = "DF_ALLOW_TREE_SUM";
    public static final String DF_VISIBLE = "DF_VISIBLE";
    public static final String DF_ENCRYPTED = "DF_ENCRYPTED";
    public static final String DF_ZB_TYPE = "DF_ZB_TYPE";
    public static final String DF_ZB_VERSION = "DF_ZB_VERSION";
    public static final String DF_ZB_FORMULA = "DF_ZB_FORMULA";
    public static final String DF_ZB_FORMULA_DESC = "DF_ZB_FORMULA_DESC";
    public static final String DF_DATA_MASK_CODE = "DF_MASK_CODE";
    public static final String DF_RESTRICT_TYPE = "DF_RESTRICT_TYPE";
    public static final String DF_REF_PARAMETER = "DF_REF_PARAMETER";
    public static final String NR_DATASCHEME_DIM_DES = "NR_DATASCHEME_DIM_DES";
    public static final String NR_DATASCHEME_DIM = "NR_DATASCHEME_DIM";
    private static final String NR_DATASCHEME_DIM_PER = "DD_";
    public static final String DD_DS_KEY = "DD_DS_KEY";
    public static final String DD_TYPE = "DD_TYPE";
    public static final String DD_DIM_KEY = "DD_DIM_KEY";
    public static final String DD_PERIOD_TYPE = "DD_PERIOD_TYPE";
    public static final String DD_PERIOD_PATTERN = "DD_PERIOD_PATTERN";
    public static final String DD_VERSION = "DD_VERSION";
    public static final String DD_LEVEL = "DD_LEVEL";
    public static final String DD_ORDER = "DD_ORDER";
    public static final String DD_UPDATE_TIME = "DD_UPDATE_TIME";
    public static final String DD_REPORT_DIM = "DD_REPORT_DIM";
    public static final String DD_DIM_ATTRIBUTE = "DD_DIM_ATTRIBUTE";
    public static final String NR_DATASCHEME_DEPLOY_INFO = "NR_DATASCHEME_DEPLOY_INFO";
    public static final String DSDI_DS_KEY = "DS_DS_KEY";
    public static final String DSDI_DT_KEY = "DS_DT_KEY";
    public static final String DSDI_SDT_KEY = "DS_SDT_KEY";
    public static final String DSDI_DF_KEY = "DS_DF_KEY";
    public static final String DSDI_TM_KEY = "DS_TM_KEY";
    public static final String DSDI_CM_KEY = "DS_CM_KEY";
    public static final String DSDI_FIELD_NAME = "DS_FIELD_NAME";
    public static final String DSDI_TABLE_NAME = "DS_TABLE_NAME";
    public static final String DSDI_VERSION = "DS_VERSION";
    public static final String DSDI_UPDATE_TIME = "DS_UPDATE_TIME";
    public static final String NR_DATASCHEME_DEPLOY_STATUS = "NR_DATASCHEME_DEPLOY_STATUS";
    public static final String DSDS_DS_KEY = "DS_DS_KEY";
    public static final String DSDS_DEPLOY_STATUS = "DS_DEPLOY_STATUS";
    public static final String DSDS_UPDATE_TIME = "DS_UPDATE_TIME";
    public static final String DSDS_LAST_UPDATE_TIME = "DS_LAST_UPDATE_TIME";
    public static final String DSDS_DEPLOY_DETAILS = "DS_DEPLOY_DETAILS";
    public static final String DATA_SCHEME_I18N = "NR_DATASCHEME_I18N";
    public static final String DATA_SCHEME_I18N_DES = "NR_DATASCHEME_I18N_DES";
    public static final String DI_KEY = "DI_KEY";
    public static final String DI_TYPE = "DI_TYPE";
    public static final String DI_TITLE = "DI_TITLE";
    public static final String DI_DESC = "DI_DESC";
    public static final String DI_DS_KEY = "DI_DS_KEY";
    public static final String NR_DATASCHEME_TABLE_REL = "NR_DATASCHEME_TABLE_REL";
    public static final String NR_DATASCHEME_TABLE_REL_DES = "NR_DATASCHEME_TABLE_REL_DES";
    public static final String DTR_KEY = "DTR_KEY";
    public static final String DTR_TYPE = "DTR_TYPE";
    public static final String DTR_DS_KEY = "DTR_DS_KEY";
    public static final String DTR_SRCTABLE_KEY = "DTR_SRCTABLE_KEY";
    public static final String DTR_DESTTABLE_KEY = "DTR_DESTTABLE_KEY";
    public static final String DTR_SRCFIELD_KEYS = "DTR_SRCFIELD_KEYS";
    public static final String DTR_DESTFIELD_KEYS = "DTR_DESTFIELD_KEYS";
    public static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneOffset.systemDefault());
    public static final String REG_0 = "^[A-Za-z]\\w{0,19}";
    public static final String REG_1 = "^[A-Za-z]\\w{0,3}";
    public static final String REG_2 = "^[A-Za-z]\\w{0,49}";
    public static final String REG_3 = "^[A-Za-z]\\w{0,30}";
    public static final String TABLE_SERVICE_NO_CACHE = "RuntimeDataTableServiceImpl-NO_CACHE";
    public static final String FIELD_SERVICE_NO_CACHE = "RuntimeDataFieldServiceImpl-NO_CACHE";
    public static final String SCHEME_SERVICE_NO_CACHE = "RuntimeSchemeServiceImpl-NO_CACHE";
    public static final String TABLEREL_SERVICE_NO_CACHE = "RuntimeDataTableRelServiceImpl-NO_CACHE";
    public static final String RUNTIME_SERVICE_NO_CACHE = "RuntimeDataSchemeNoCacheServiceImpl-NO_CACHE";
    public static final String CHANNEL = "com.jiuqi.nr.datascheme.runtime";
    public static final String FMDM_PREFIX = "FMDM_";
    public static final String NR_ADJUST_PERIOD = "NR_ADJUST_PERIOD";
    public static final String NR_ADJUST_PERIOD_DES = "NR_ADJUST_PERIOD_DES";
    public static final String AP_DS_KEY = "AP_DS_KEY";
    public static final String AP_PERIOD = "AP_PERIOD";
    public static final String AP_CODE = "AP_CODE";
    public static final String AP_TITLE = "AP_TITLE";
    public static final String AP_ORDER = "AP_ORDER";
    public static final String NR_DATASCHEME_TABLE_MAP = "NR_DATASCHEME_TABLE_MAP";
    public static final String MAP_SRC_KEY = "MAP_SRC_KEY";
    public static final String MAP_TABLE_KEY = "MAP_TABLE_KEY";
    public static final String MAP_TABLE_CODE = "MAP_TABLE_CODE";
    public static final String MAP_SRC_TYPE = "MAP_SRC_TYPE";
    public static final String MAP_SCHEME_KEY = "MAP_SCHEME_KEY";
    public static final String MAP_SRC_CODE = "MAP_SRC_CODE";
    public static final String NR_DATASCHEME_TABLE_CAL_RESULT = "NR_DATASCHEME_TABLE_CAL_RESULT";
    public static final String CAL_KEY = "C_KEY";
    public static final String CAL_DS_KEY = "DS_KEY";
    public static final String CAL_RESULT = "C_RESULT";
    public static final String CAL_UPDATE_TIME = "C_UPDATE_TIME";
    public static final String CAL_MESSAGE = "C_MESSAGE";
    public static final String MD_ORG = "MD_ORG@ORG";

    public static DataGroup getDataSchemeRootGroup() {
        DataGroupDTO group = new DataGroupDTO();
        group.setKey(DATASCHEME_ROOT_GROUP);
        group.setTitle(DATASCHEME_ROOT_GROUP_TITLE);
        group.setCode("ROOT");
        group.setDataGroupKind(DataGroupKind.SCHEME_GROUP);
        group.setOrder(MD_ADJUST_DEFAULT_VALUE);
        return group;
    }

    public static DataGroup getQueryDataSchemeRootGroup() {
        DataGroupDTO group = new DataGroupDTO();
        group.setKey(QUERY_DATASCHEME_ROOT_GROUP);
        group.setTitle(QUERY_DATASCHEME_ROOT_GROUP_TITLE);
        group.setCode("QUERY_ROOT");
        group.setDataGroupKind(DataGroupKind.SCHEME_GROUP);
        group.setOrder("1");
        return group;
    }
}

